version: '3.9'

services:
  mysql1:
    image: mysql:8.0
    container_name: masql8
    ports:
      - "3306:3306"
    #    jdbc:mysql://localhost:3306/chat2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat2
    volumes:
      - "/home/mysql1:/var/lib/mysql"

  redis1:
    image: "redis:alpine3.14"
    container_name: redis1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cassandra1:
    image: "cassandra:3.11"
    container_name: cassandra1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  back1:
    image: 'back1'
    container_name: back1
    build:
      context: 10060Back1JavaSpring
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - MYSQL_HOST=mysql1
      - REDIS_HOST=redis1
    ports:
      - "8080:8080"
    depends_on:
      - mysql1
    volumes:
      - ./:/app

  rabbitmq1:
    image: "rabbitmq:3.9.3"
    container_name: rabbitmq1_chat2
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    volumes:
      - "./10060Back1JavaSpring/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - rabbit_data_chat2:/var/lib/rabbitmq/

volumes:
  redis_data:
  cassandra_data:
  rabbit_data_chat2: