server:
  port: 8080
  servlet:
    context-path:

spring:
#  config:
#    activate:
#      on-profile: dev
  application:
    name: back1
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/chat2
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 3600000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: true
  jackson:
    serialization:
      indent_output: true


  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  data:
    cassandra:
      contact-points: localhost
#      local-datacenter: datacenter1
#      keyspace-name: default
      username: cassandra
      password: cassandra
      schema-action:  none
      port: 9042
    redis:
      repositories:
        enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql


